language: perl
services:
    - docker
sudo: required
perl:
    - '5.30'
    - '5.28'
    - '5.26'
    - '5.24'
    - '5.22'
    - '5.20'
before_install: eval $(curl https://travis-perl.github.io/init) --auto
install: cpanm -n --skip-satisfied Devel::Cover::Report::Coveralls
script:
    - PERL5OPT=-MDevel::Cover prove -lv t
    - ./run-xt
after_success: cover -report coveralls -select_re ^lib/
